/**
 * Security Specialist Agent Data
 * 
 * Security-focused agent to lead product security development and documentation.
 */

import { AgentType, GuideCategory } from '@prisma/client'

export const securityAgentData = {
  type: AgentType.SECURITY_SPECIALIST,
  name: 'The Security Specialist',
  description: 'Expert security professional specializing in financial data protection, compliance, and secure product development. Leads security implementation and documentation for all products.',
  expertise: 'Data encryption, access control, compliance (SOC2, GDPR, PCI-DSS), security architecture, threat modeling, vulnerability assessment, incident response, security auditing, secure development lifecycle (SDLC), penetration testing, security documentation',
  avatar: '🔒',
  order: 8,
  metadata: {
    proTips: [
      'Encrypt data at rest and in transit - use AES-256 for at-rest and TLS 1.3 for in-transit',
      'Implement least privilege access - users should only have access to what they need',
      'Use multi-factor authentication (MFA) for all financial data access',
      'Conduct regular security audits and penetration testing - security is not a one-time event',
      'Document all security procedures - if it\'s not documented, it doesn\'t exist',
      'Implement comprehensive audit logging - track all access to sensitive financial data',
      'Follow defense in depth - multiple layers of security controls',
      'Keep security dependencies updated - patch vulnerabilities promptly',
      'Use secure coding practices - OWASP Top 10 awareness is essential',
      'Implement proper session management - secure tokens, timeouts, and revocation',
    ],
    whatToAvoid: [
      'Storing sensitive data in plain text - always encrypt financial data',
      'Weak authentication mechanisms - avoid single-factor authentication for financial products',
      'Exposing sensitive data in logs or error messages',
      'Hardcoding credentials or API keys in source code',
      'Ignoring security warnings or deprecation notices',
      'Skipping security reviews for new features or products',
      'Using outdated encryption algorithms or protocols',
      'Failing to implement rate limiting and DDoS protection',
      'Not having an incident response plan',
      'Assuming third-party services are secure without verification',
    ],
    bestPractices: [
      'Follow OWASP security guidelines for web applications',
      'Implement role-based access control (RBAC) for all products',
      'Use secure password hashing (bcrypt, Argon2) - never store plain passwords',
      'Implement input validation and sanitization - prevent injection attacks',
      'Use Content Security Policy (CSP) headers to prevent XSS attacks',
      'Implement CORS policies correctly - don\'t allow wildcard origins',
      'Use parameterized queries to prevent SQL injection',
      'Implement proper error handling - don\'t leak system information',
      'Conduct threat modeling for each product before development',
      'Maintain a security changelog and document all security-related changes',
      'Regularly review and update security documentation',
      'Train development teams on secure coding practices',
      'Implement automated security scanning in CI/CD pipelines',
      'Use secrets management systems (AWS Secrets Manager, HashiCorp Vault)',
      'Implement network segmentation and firewall rules',
    ],
  },
  guides: [
    {
      title: 'Secure Product Development Lifecycle',
      description: 'Complete guide to building secure financial products from design to deployment',
      category: GuideCategory.BUSINESS_DEVELOPMENT,
      difficulty: 5,
      estimatedTime: 180,
      steps: [
        {
          id: '1',
          title: 'Threat Modeling',
          description: 'Identify potential security threats and vulnerabilities',
          instructions: 'Conduct threat modeling session: identify assets, threats, vulnerabilities, and mitigation strategies. Document using STRIDE methodology.',
          isOptional: false,
          order: 0,
        },
        {
          id: '2',
          title: 'Security Architecture Design',
          description: 'Design secure architecture with defense in depth',
          instructions: 'Design security architecture: encryption, authentication, authorization, network security, and monitoring. Document security controls.',
          isOptional: false,
          order: 1,
        },
        {
          id: '3',
          title: 'Secure Coding Standards',
          description: 'Establish and follow secure coding practices',
          instructions: 'Define secure coding standards, use static analysis tools, implement code reviews with security focus, and train developers.',
          isOptional: false,
          order: 2,
        },
        {
          id: '4',
          title: 'Security Testing',
          description: 'Implement comprehensive security testing',
          instructions: 'Perform security testing: static analysis, dynamic analysis, penetration testing, and vulnerability scanning. Fix identified issues.',
          isOptional: false,
          order: 3,
        },
        {
          id: '5',
          title: 'Security Documentation',
          description: 'Document all security procedures and controls',
          instructions: 'Create security documentation: architecture, procedures, incident response plan, compliance status, and security reviews.',
          isOptional: false,
          order: 4,
        },
        {
          id: '6',
          title: 'Deployment and Monitoring',
          description: 'Deploy securely and monitor for security events',
          instructions: 'Deploy with security controls enabled, configure monitoring and alerting, implement audit logging, and establish incident response procedures.',
          isOptional: false,
          order: 5,
        },
      ],
    },
    {
      title: 'Financial Data Protection Compliance',
      description: 'Guide to achieving and maintaining compliance with financial data protection regulations',
      category: GuideCategory.BUSINESS_DEVELOPMENT,
      difficulty: 5,
      estimatedTime: 240,
      steps: [
        {
          id: '1',
          title: 'Identify Applicable Regulations',
          description: 'Determine which regulations apply to your product',
          instructions: 'Identify applicable regulations: GDPR (EU users), PCI-DSS (payment data), SOC2 (service providers), HIPAA (health data), and local financial regulations.',
          isOptional: false,
          order: 0,
        },
        {
          id: '2',
          title: 'Gap Analysis',
          description: 'Assess current state vs. compliance requirements',
          instructions: 'Conduct gap analysis: compare current security controls with regulatory requirements. Document gaps and create remediation plan.',
          isOptional: false,
          order: 1,
        },
        {
          id: '3',
          title: 'Implement Compliance Controls',
          description: 'Implement required security and privacy controls',
          instructions: 'Implement compliance controls: data encryption, access controls, audit logging, data retention policies, and privacy controls.',
          isOptional: false,
          order: 2,
        },
        {
          id: '4',
          title: 'Documentation and Policies',
          description: 'Create compliance documentation and policies',
          instructions: 'Document compliance: privacy policy, data processing agreements, security policies, incident response procedures, and compliance reports.',
          isOptional: false,
          order: 3,
        },
        {
          id: '5',
          title: 'Compliance Auditing',
          description: 'Conduct compliance audits and assessments',
          instructions: 'Schedule and conduct compliance audits: internal audits, third-party assessments, and regulatory reviews. Address findings.',
          isOptional: false,
          order: 4,
        },
        {
          id: '6',
          title: 'Ongoing Compliance',
          description: 'Maintain compliance through continuous monitoring',
          instructions: 'Maintain compliance: regular audits, security reviews, policy updates, training, and monitoring compliance metrics.',
          isOptional: false,
          order: 5,
        },
      ],
    },
  ],
}


