/**
 * System Configuration
 *
 * Maps each system to its filter values (team domains, agent types) for useSystemData.
 */

export const FINANCE_TEAM_DOMAINS = [
  'INVESTMENT',
  'TAX_OPTIMIZATION',
  'CASH_FLOW',
  'BUSINESS_ADVISORY',
  'COMPREHENSIVE_PLANNING',
  'DEBT_MANAGEMENT',
  'EMERGENCY_FUND',
  'CORE_MONEY_SYSTEM',
] as const

export const FINANCE_AGENT_TYPES = [
  'INVESTOR',
  'FINANCIAL_ADVISOR',
  'ACCOUNTANT',
  'BOOKKEEPER',
  'TAX_STRATEGIST',
  'CASH_FLOW_SPECIALIST',
  'DEBT_SPECIALIST',
  'SECURITY_SPECIALIST',
] as const

export const HEALTH_TEAM_DOMAINS = [
  'HEALTH_CAPACITY',
  'HEALTH_NUTRITION',
  'HEALTH_MOVEMENT',
  'HEALTH_SLEEP',
  'HEALTH_MENTAL',
] as const
export const HEALTH_AGENT_TYPES = [
  'CAPACITY_SPECIALIST',
  'RECOVERY_COACH',
  'BURNOUT_PREVENTION_SPECIALIST',
] as const

export const SOFTWARE_TEAM_DOMAINS = [
  'PLATFORM_ENGINEERING',
  'SOFTWARE_ARCHITECTURE',
  'SOFTWARE_DELIVERY',
  'SOFTWARE_QUALITY',
  'SOFTWARE_API_DESIGN',
] as const
export const SOFTWARE_AGENT_TYPES = ['SOFTWARE_ARCHITECT', 'DEVOPS_ENGINEER', 'QA_ENGINEER'] as const

export const OPTIONALITY_TEAM_DOMAINS = [
  'DECISION_ANALYSIS',
  'SKILL_DEVELOPMENT',
  'PROOF_BUILDING',
  'OPTIONALITY_CAPITAL',
  'OPTIONALITY_NETWORK',
] as const
export const OPTIONALITY_AGENT_TYPES = [
  'DECISION_ANALYST',
  'RISK_STRATEGIST',
  'SYSTEMS_THINKER',
  'LEARNING_ARCHITECT',
  'SPECIALIZATION_ADVISOR',
  'PROGRESS_TRACKER',
  'ARTIFACT_DESIGNER',
  'IMPACT_ANALYST',
  'VISIBILITY_STRATEGIST',
] as const

export const TRUST_TEAM_DOMAINS = [
  'TRUST_BUILDING',
  'TRUST_ALIGNMENT',
  'TRUST_COMMUNICATION',
  'TRUST_DELIVERY',
  'EGO_MANAGEMENT',
] as const
export const TRUST_AGENT_TYPES = [
  'TRUST_ANALYST',
  'RELIABILITY_COACH',
  'ALIGNMENT_STRATEGIST',
  'REPUTATION_GUARDIAN',
  'FAILURE_ANALYST',
  'COMMUNICATION_SPECIALIST',
  'EGO_COACH',
  'FEEDBACK_PROCESSOR',
  'COURSE_CORRECTOR',
] as const

export const REPUTATION_TEAM_DOMAINS = [
  'REPUTATION_DEFENSE',
  'REPUTATION_SIGNAL',
  'REPUTATION_RECOVERY',
  'REPUTATION_VISIBILITY',
  'REPUTATION_TRUST',
] as const

export const ENERGY_TEAM_DOMAINS = [
  'ENERGY_MANAGEMENT',
  'ENERGY_RECOVERY',
  'ENERGY_FOCUS',
  'ENERGY_RHYTHM',
  'ENERGY_ENVIRONMENT',
] as const
export const ENERGY_AGENT_TYPES = ['ENERGY_ANALYST', 'ENERGY_COACH', 'ENERGY_RECOVERY_COACH'] as const

export const TRAVEL_TEAM_DOMAINS = [
  'TRAVEL_PLANNING',
  'TRAVEL_LOGISTICS',
  'TRAVEL_SAFETY',
  'TRAVEL_COST',
  'TRAVEL_EXPERIENCE',
] as const
export const TRAVEL_AGENT_TYPES = ['TRAVEL_PLANNER', 'TRAVEL_LOGISTICS_COORDINATOR', 'TRAVEL_SAFETY_ADVISOR'] as const

export const MEANING_TEAM_DOMAINS = [
  'MEANING_ALIGNMENT',
  'MEANING_PRACTICE',
  'MEANING_REFLECTION',
  'MEANING_COMMUNITY',
  'MEANING_PURPOSE',
] as const
export const MEANING_AGENT_TYPES = ['PURPOSE_GUIDE', 'VALUES_COACH', 'REFLECTION_FACILITATOR'] as const
