/**
 * System Configuration
 *
 * Maps each system to its filter values (team domains, agent types) for useSystemData.
 */

export const FINANCE_TEAM_DOMAINS = [
  'INVESTMENT',
  'TAX_OPTIMIZATION',
  'CASH_FLOW',
  'BUSINESS_ADVISORY',
  'COMPREHENSIVE_PLANNING',
  'DEBT_MANAGEMENT',
  'EMERGENCY_FUND',
  'PLATFORM_ENGINEERING',
  'CORE_MONEY_SYSTEM',
] as const

export const FINANCE_AGENT_TYPES = [
  'INVESTOR',
  'FINANCIAL_ADVISOR',
  'ACCOUNTANT',
  'BOOKKEEPER',
  'TAX_STRATEGIST',
  'CASH_FLOW_SPECIALIST',
  'DEBT_SPECIALIST',
  'SECURITY_SPECIALIST',
] as const

export const HEALTH_TEAM_DOMAINS = ['HEALTH_CAPACITY'] as const
export const HEALTH_AGENT_TYPES = [
  'CAPACITY_SPECIALIST',
  'RECOVERY_COACH',
  'BURNOUT_PREVENTION_SPECIALIST',
] as const

export const OPTIONALITY_TEAM_DOMAINS = [
  'DECISION_ANALYSIS',
  'SKILL_DEVELOPMENT',
  'PROOF_BUILDING',
] as const
export const OPTIONALITY_AGENT_TYPES = [
  'DECISION_ANALYST',
  'RISK_STRATEGIST',
  'SYSTEMS_THINKER',
  'LEARNING_ARCHITECT',
  'SPECIALIZATION_ADVISOR',
  'PROGRESS_TRACKER',
  'ARTIFACT_DESIGNER',
  'IMPACT_ANALYST',
  'VISIBILITY_STRATEGIST',
] as const

export const TRUST_TEAM_DOMAINS = [
  'TRUST_BUILDING',
  'REPUTATION_DEFENSE',
  'EGO_MANAGEMENT',
] as const
export const TRUST_AGENT_TYPES = [
  'TRUST_ANALYST',
  'RELIABILITY_COACH',
  'ALIGNMENT_STRATEGIST',
  'REPUTATION_GUARDIAN',
  'FAILURE_ANALYST',
  'COMMUNICATION_SPECIALIST',
  'EGO_COACH',
  'FEEDBACK_PROCESSOR',
  'COURSE_CORRECTOR',
] as const
