/**
 * Glossary View - Standalone reference for key terms and concepts
 * 
 * Provides a comprehensive reference of all game terminology including:
 * - Resources (Energy, Money, Oxygen, Water, Armor, Keys)
 * - Stats (Capacity, Engines, Meaning, Optionality)
 * - Systems (Money System, Energy System)
 * - Concepts (Tier System, Laws, Principles)
 * - Game Mechanics (Daily Tick, Weekly Tick, Seasons, Burnout, XP)
 */

import { Shield, Target, Layers, BookOpen, Zap, Info } from 'lucide-react'

export default function GlossaryView() {
  return (
    <div className="max-w-5xl mx-auto">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-4 mb-4">
          <div className="p-4 bg-blue-500/20 rounded-lg">
            <Info className="w-8 h-8 text-blue-400" />
          </div>
          <div>
            <h1 className="text-4xl font-bold text-white">Glossary</h1>
            <p className="text-gray-400 mt-2">
              Comprehensive reference for all key terms, concepts, and game mechanics in Life World OS
            </p>
          </div>
        </div>
      </div>

      {/* Glossary Content */}
      <div className="bg-gray-800 rounded-lg border-2 border-gray-700 p-8">
        <div className="space-y-8">
          {/* Resources */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-3 flex items-center gap-3">
              <Shield className="w-6 h-6 text-blue-400" />
              Resources
            </h2>
            <p className="text-gray-400 mb-6">
              Trackable quantities used for costs, buffers, and progression. Resources can be spent, accumulated, or decay over time.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-yellow-400 mb-2">Energy</h3>
                <p className="text-sm text-gray-300">
                  Daily budget (0-110) that enables all actions. Resets at daily tick. Cannot stack across days. Modified by Capacity stat.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-green-400 mb-2">Money (Gold)</h3>
                <p className="text-sm text-gray-300">
                  Primary currency of the Power Game. Generated by Engines. Used for investments and purchases. Enables influence and control.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-blue-400 mb-2">Oxygen</h3>
                <p className="text-sm text-gray-300">
                  Financial safety net measured in months of expenses. Primary survival buffer. Decays daily if not maintained. Enables risk-taking when high.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-cyan-400 mb-2">Water</h3>
                <p className="text-sm text-gray-300">
                  Health and vitality score (0-100). Low Water triggers Winter season and blocks progression. Affected by exercise and recovery.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-purple-400 mb-2">Armor</h3>
                <p className="text-sm text-gray-300">
                  Systems, buffers, boundaries (0-100). Protects against stress events. Reduces failure state penalties. Built through systems and boundaries.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-orange-400 mb-2">Keys</h3>
                <p className="text-sm text-gray-300">
                  Unlocked options and opportunities (count). Enables new pathways. Gained through achievements. Increases optionality and opens new system access.
                </p>
              </div>
            </div>
          </section>

          {/* Stats */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-3 flex items-center gap-3">
              <Target className="w-6 h-6 text-pink-400" />
              Stats
            </h2>
            <p className="text-gray-400 mb-6">
              Levers that modify system behavior. All stats range from 0-100 and influence how the system responds to actions and events.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-blue-400 mb-2">Capacity</h3>
                <p className="text-sm text-gray-300">
                  Health, energy, resilience (0-100). Governs energy regeneration and survival capability. Low Capacity = survival risk. Affects burnout resistance and recovery speed.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-green-400 mb-2">Engines</h3>
                <p className="text-sm text-gray-300">
                  Income generation capability (0-100). Governs multiple income sources (Career, Business, Investment, Learning). High Engines unlocks higher-value actions.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-purple-400 mb-2">Meaning</h3>
                <p className="text-sm text-gray-300">
                  Purpose and values alignment (0-100). Provides burnout resistance. Prevents decay when actions align with values. Cannot be bought with money.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-yellow-400 mb-2">Optionality</h3>
                <p className="text-sm text-gray-300">
                  Available choices and pathways (0-100). Increases with investments, keys, and unlocked systems. Enables asymmetric outcomes and freedom.
                </p>
              </div>
            </div>
          </section>

          {/* Systems */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-3 flex items-center gap-3">
              <Layers className="w-6 h-6 text-blue-400" />
              Systems
            </h2>
            <p className="text-gray-400 mb-6">
              Executable, state-changing systems. Actions occur, consequences apply. Consumes energy, affected by capacity, subject to decay and burnout.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-green-400 mb-2">Money System</h3>
                <p className="text-sm text-gray-300">
                  Financial guidance with AI agents, domain teams, and interactive products. Includes 7 Expert AI Agents, 8 Domain Teams, 17 Financial Products, and security features.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-yellow-400 mb-2">Energy System</h3>
                <p className="text-sm text-gray-300">
                  Track and manage energy levels, capacity, and vitality. Includes energy tracking, capacity management, weekly ticks, burnout prevention, and recovery actions.
                </p>
              </div>
            </div>
          </section>

          {/* Laws */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-3 flex items-center gap-3">
              <BookOpen className="w-6 h-6 text-orange-400" />
              Laws
            </h2>
            <p className="text-gray-400 mb-6">
              Immutable rules that govern behavior and outcomes across all domains.
            </p>
            <div className="space-y-4">
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-orange-400 mb-2">48 Laws of Power</h3>
                <p className="text-sm text-gray-300">
                  48 strategic laws applied across domains: Money, Career, Business, Relationships, Leadership, Negotiation, and Energy. Governs influence, control, and strategic positioning.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-orange-400 mb-2">Bible Laws</h3>
                <p className="text-sm text-gray-300">
                  Biblical laws applied to financial and life domains. Covers Money, Investment, Career, Business, Relationships, Leadership, Spiritual Growth, Stewardship, and Generosity.
                </p>
              </div>
            </div>
          </section>

          {/* Principles */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-3 flex items-center gap-3">
              <BookOpen className="w-6 h-6 text-cyan-400" />
              Principles
            </h2>
            <p className="text-gray-400 mb-6">
              Fundamental truths that guide decision-making and strategic thinking.
            </p>
            <div className="space-y-4">
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-cyan-400 mb-2">Universal Principles</h3>
                <p className="text-sm text-gray-300">
                  Timeless principles that govern success, growth, and sustainable performance across all domains. Includes Compound Growth, Energy Conservation, Risk-Return Tradeoff, Progressive Overload, and Sustainable Balance.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-cyan-400 mb-2">Financial Principles</h3>
                <p className="text-sm text-gray-300">
                  Core principles for wealth building and financial decision-making. Covers Time Value of Money, Asymmetric Risk-Reward, Diversification, Cash Flow Management, and Compound Interest.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-cyan-400 mb-2">Energy Principles</h3>
                <p className="text-sm text-gray-300">
                  Fundamental principles for managing capacity and sustainable performance. Covers Recovery &gt; Depletion, Energy Conservation, Sustainable Rhythm, Capacity Building, and Burnout Prevention.
                </p>
              </div>
            </div>
          </section>

          {/* Frameworks */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-3 flex items-center gap-3">
              <BookOpen className="w-6 h-6 text-indigo-400" />
              Frameworks
            </h2>
            <p className="text-gray-400 mb-6">
              Structured approaches for analysis, problem-solving, and strategic planning.
            </p>
            <div className="space-y-4">
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-indigo-400 mb-2">Financial Frameworks</h3>
                <p className="text-sm text-gray-300">
                  Strategic frameworks for investment, cash flow management, and wealth building. Includes Portfolio Management, Cash Flow Optimization, Debt Strategy, Asset Allocation, and Risk Assessment.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-indigo-400 mb-2">Energy Frameworks</h3>
                <p className="text-sm text-gray-300">
                  Structured approaches for capacity management and performance optimization. Includes Capacity Management, Recovery Planning, Performance Optimization, Energy Allocation, and Burnout Prevention.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-indigo-400 mb-2">Strategic Frameworks</h3>
                <p className="text-sm text-gray-300">
                  High-level frameworks for decision-making and goal achievement. Includes SMART Goals, Decision Matrix, Strategic Planning, Priority Management, and Risk-Opportunity Analysis.
                </p>
              </div>
            </div>
          </section>

          {/* Concepts */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-3 flex items-center gap-3">
              <BookOpen className="w-6 h-6 text-purple-400" />
              Concepts
            </h2>
            <p className="text-gray-400 mb-6">
              Abstract ideas and mental models for understanding system behavior.
            </p>
            <div className="space-y-4">
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-purple-400 mb-2">Tier System</h3>
                <p className="text-sm text-gray-300 mb-3">
                  Universal system hierarchy that determines action priorities and system progression.
                </p>
                <ul className="text-sm text-gray-400 space-y-1 ml-4">
                  <li>• <strong className="text-red-400">Tier 0 (Survival)</strong>: Non-negotiable baseline requirements</li>
                  <li>• <strong className="text-orange-400">Tier 1 (Stability)</strong>: Variance control and consistency</li>
                  <li>• <strong className="text-yellow-400">Tier 2 (Growth)</strong>: Compounding and expansion</li>
                  <li>• <strong className="text-green-400">Tier 3 (Leverage)</strong>: Asymmetric outcomes and scaling</li>
                  <li>• <strong className="text-blue-400">Tier 4 (Expression)</strong>: Freedom and preference-driven actions</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Game Mechanics */}
          <section>
            <h2 className="text-2xl font-bold text-white mb-3 flex items-center gap-3">
              <Zap className="w-6 h-6 text-yellow-400" />
              Game Mechanics
            </h2>
            <p className="text-gray-400 mb-6">
              Core mechanics that govern how the system operates and enforces constraints.
            </p>
            <div className="space-y-4">
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-blue-400 mb-2">Daily Tick</h3>
                <p className="text-sm text-gray-300">
                  Runs once per calendar day. Applies decay and regeneration. Resets daily Energy pool. Missed ticks are replayed deterministically to maintain game state integrity.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-purple-400 mb-2">Weekly Tick</h3>
                <p className="text-sm text-gray-300">
                  Runs every 7 daily ticks. Evaluates imbalance and failure accumulation. Applies over-optimization penalties. Enforces seasonal transitions if conditions are met.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-green-400 mb-2">Seasons</h3>
                <p className="text-sm text-gray-300 mb-3">
                  Cyclical modes with explicit rules and minimum duration requirements:
                </p>
                <ul className="text-sm text-gray-400 space-y-1 ml-4">
                  <li>• <strong className="text-green-300">Spring</strong>: Planning & Preparation phase</li>
                  <li>• <strong className="text-yellow-300">Summer</strong>: Peak Output and maximum productivity</li>
                  <li>• <strong className="text-orange-300">Autumn</strong>: Harvest & Consolidation period</li>
                  <li>• <strong className="text-blue-300">Winter</strong>: Rest & Recovery (forced when Water is low)</li>
                </ul>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-red-400 mb-2">Burnout</h3>
                <p className="text-sm text-gray-300">
                  Failure state triggered by excessive energy expenditure or low Capacity. Reduces energy cap to 40, penalizes XP gain by 50%, and blocks Work actions until recovery actions are taken.
                </p>
              </div>
              <div className="bg-gray-700/50 rounded-lg p-4">
                <h3 className="text-lg font-semibold text-yellow-400 mb-2">XP System</h3>
                <p className="text-sm text-gray-300">
                  Overall XP pool from all activities. Overall Rank progression (Recruit → Command Sergeant Major). Category XP for each Cloud (Capacity, Engines, Oxygen, Meaning, Optionality) with separate levels (1-50+).
                </p>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  )
}

